name: Generate Snake Animation

on:
  schedule: 
    - cron: "0 */12 * * *"  # runs every 12 hours
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Generate GitHub contribution snake
        uses: Platane/snk@v3
        with:
          github_user_name: pavanikrishnadola
          outputs: dist/snake.svg

      - name: Push generated files
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
